export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';

export const FETCH_PUBLISHERS = 'FETCH_PUBLISHERS';
export const FETCH_PUBLISHER = 'FETCH_PUBLISHER';

export const FETCH_CONFIG = 'FETCH_CONFIG';